import type { Metadata } from 'next'
import { Roboto_Condensed } from 'next/font/google'
import './globals.css'

const roboto_condensed = Roboto_Condensed({
  weight: '700',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'WebbyWolf Landing Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto_condensed.className}>{children}</body>
    </html>
  )
}